name: CURSOR PROJECTS
jobs:
  Build:
    name: Build
    steps:
      - type: node-js
        shell-script: npm install
        docker-image: node:lts
    runs-on: Linux-Medium
    dependencies:
      - CodeScan
  Test:
    name: Test
    runs-on: Linux-Medium
    steps:
      - type: node-js
        shell-script: |-
          npm install -g mocha
          npm install --save-dev start-server-and-test
        docker-image: node:lts
        name: Install Prerequisites
      - type: node-js
        shell-script: npx start-test 3000
        docker-image: node:lts
        name: Run tests
    dependencies:
      - Build
  DockerBuildPush:
    name: Docker Build & Push
    runs-on: Linux-Medium
    steps:
      - type: script
        script-content: docker build -t hello-world-node .
        name: Build
      - type: script
        name: Push
        script-content: |-
          docker tag hello-world-node:latest mitin20/hello-world-node:latest
          docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD% docker.io
          docker push mitin20/hello-world-node:latest
    dependencies:
      - Test
  DockerScan:
    name: Docker Scan
    runs-on: Linux-Medium
    steps:
      - type: script
        name: Scan image
        script-content: >-
          # Install the Docker Scout CLI

          #curl -sSfL
          https://raw.githubusercontent.com/docker/scout-cli/main/install.sh |
          sh -s --

          # Login to Docker Hub required for Docker Scout CLI

          #docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD%

          # Get a CVE report for the built image and fail the pipeline when
          critical or high CVEs are detected

          #docker scout cves mitin20/hello-world-node:latest --exit-code
          --only-severity critical,high

          # Build docker-scout-cli

          #cd scout

          #docker build --build-arg DOCKER_USERNAME=%DOCKER_USERNAME%
          --build-arg DOCKER_PASSWORD=%DOCKER_PASSWORD% -t my-scout-cli .

          # Run docker-scout-cli
          # Full scan    
          # docker run \
          #   -e DOCKER_SCOUT_HUB_USER=%DOCKER_USERNAME% \
          #   -e DOCKER_SCOUT_HUB_PASSWORD=%DOCKER_PASSWORD% \
          #   docker/scout-cli \
          #   cves mitin20/hello-world-node:latest --exit-code --only-severity critical,high
          # Quickview
          docker run \
            -e DOCKER_SCOUT_HUB_USER=%DOCKER_USERNAME% \
            -e DOCKER_SCOUT_HUB_PASSWORD=%DOCKER_PASSWORD% \
            docker/scout-cli \
            cves mitin20/hello-world-node:latest            
    dependencies:
      - DockerBuildPush
  CodeScan:
    name: Code Scan
    runs-on: Linux-Medium
    steps:
      - type: node-js
        shell-script: |-
          # Monitor local projects
          npm install -g snyk
          snyk auth %SNYK_TOKEN%
          snyk test 
          snyk monitor
        docker-image: node:lts
        name: Scan
secrets:
  DOCKER_USERNAME: credentialsJSON:aeff4c24-9874-4e1e-ae49-5cce5a63039f
  DOCKER_PASSWORD: credentialsJSON:c7c87923-d5ac-4a9a-8f8d-cbd6748222ce
  SNYK_TOKEN: credentialsJSON:11cad727-f781-4e13-a218-6a8baf0b1067
