name: CURSOR PROJECTS
jobs:
  Job1:
    name: Build
    steps:
      - type: node-js
        shell-script: npm install
        docker-image: node:lts
    runs-on: Linux-Medium
  Job2:
    name: Test
    runs-on: Linux-Medium
    steps:
      - type: node-js
        shell-script: |-
          npm install -g mocha
          npm install --save-dev start-server-and-test
        docker-image: node:lts
        name: Install Prerequisites
      - type: node-js
        shell-script: npx start-test 3000
        docker-image: node:lts
        name: Run tests
    dependencies:
      - Job1
